### ISSUE TITLE
元胞自动机

### ISSUE THREAD

**Issue by Alreall** [zhangerfa/Trands_cellular_automata#1]
请问使用的元胞自动机模型是哪个，具体是在哪里体现的

**Comment by zhangerfa** [comment]
你好哈，我想做的是一个元胞自动机的开发工具，并不是具体规则的实现
具体说，车辆的信息可以直接获取，提供仿真数据获取等接口（readme中有介绍），也就是一个类似于vissim一样的软件（只是没有交互界面，通过编程交互），通过添加自己的车辆类和车辆生成器，就可以在仿真场景中添加车辆，然后进行仿真，这些都有相关接口（之后会整理为表格补充出来）
举一个例子，如果元胞自动机规则如下：
v(t+1) = min(v(t) + 1, gap, v_max)
这个规则是需要自己写出来的，不过前车距（gap）的获取是可以直接通过接口获得：
`gap = self.get_gap()
self.v = min(self.v + 1,gap,  self.v_max )`

**Comment by Alreall** [comment]
好的好的，谢谢您，期待您的更新



| |
李召
18255786547
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月21日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zhangerfa/Trands_cellular_automata] 元胞自动机 (Issue #1) |

你好哈，我想做的是一个元胞自动机的开发工具，并不是具体规则的实现
具体说，车辆的信息可以直接获取，提供仿真数据获取等接口（readme中有介绍），也就是一个类似于vissim一样的软件（只是没有交互界面，通过编程交互），通过添加自己的车辆类和车辆生成器，就可以在仿真场景中添加车辆，然后进行仿真，这些都有相关接口（之后会整理为表格补充出来）
举一个例子，如果元胞自动机规则如下：
v(t+1) = min(v(t) + 1, gap, v_max)
这个规则是需要自己写出来的，不过前车距（gap）的获取是可以直接通过接口获得：
gap = self.get_gap() self.v = min(self.v + 1,gap, self.v_max )

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alreall** [comment]
请问对向行驶的车间距计算公式v1.x-v2.x-1,其中的1代表什么

**Comment by zhangerfa** [comment]
> 

是v1 和 v2 是变量，v1就是第一辆车的车速

**Comment by Alreall** [comment]
不是太能看懂write_data那一块，还有detector那里的数据处理方法也不是很清楚，绘制密度-流量图及其他的图是不是要首先将数据处理为相应的格式，例如excel表格的形式再调用来绘图呀，最近在做这方面的毕设，所以问的有点多hhh，麻烦您了，感谢！

**Comment by Alreall** [comment]
在不同的路段汽车行驶会有限速的情况，感觉您也可以考虑一下

**Comment by Alreall** [comment]
请问是不是没有对前车的速度进行设置呀
